package org.osm2world.osm.creation;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import org.osm2world.osm.data.OSMData;
import org.osm2world.util.json.JsonUtil;

import com.slimjars.dist.gnu.trove.list.TLongList;
import com.slimjars.dist.gnu.trove.list.array.TLongArrayList;

import de.topobyte.osm4j.core.model.iface.*;
import de.topobyte.osm4j.core.model.impl.*;

/**
 * Parses OSM JSON files such as those generated by Overpass API
 * (see the <a href=https://dev.overpass-api.de/output_formats.html#json>Overpass API documentation</a>)
 */
public abstract class JsonReader implements OSMDataReader {

	protected abstract String getJsonString() throws IOException;

	@Override
	public OSMData getAllData() throws IOException {

		try {

			String json = getJsonString();
			OsmJson root = JsonUtil.deserialize(json, OsmJson.class);

			if (0.6 != root.version) {
				throw new IOException("Unsupported OSM JSON version: " + root.version);
			}

			Collection<OsmBounds> bounds = new ArrayList<>();

			Collection<OsmNode> nodes = new ArrayList<>();
			Collection<OsmWay> ways = new ArrayList<>();
			Collection<OsmRelation> relations = new ArrayList<>();

			for (OsmJsonElement e : root.elements) {

				long id = e.id;

				List<Tag> tags = new ArrayList<>();
				for (var t : e.tags.entrySet()) {
					tags.add(new Tag(t.getKey(), t.getValue()));
				}

				switch (e.type) {

					case "node" ->
						nodes.add(new Node(id,
								e.lon,
								e.lat,
								tags));

					case "way" -> {
						TLongList nodeIds = new TLongArrayList();
						for (long nodeId : e.nodes) {
							nodeIds.add(nodeId);
						}
						ways.add(new Way(id, nodeIds, tags));
					}

					case "relation" -> {
						List<OsmRelationMember> members = new ArrayList<>();
						for (OsmJsonMember m : e.members) {
							EntityType entityType = switch (m.type) {
								case "node" -> EntityType.Node;
								case "way" -> EntityType.Way;
								case "relation" -> EntityType.Relation;
								default -> throw new IOException("Invalid member type for r " + id + ": " + m.type);
							};
							long ref = m.ref;
							members.add(new RelationMember(
									ref,
									entityType,
									m.role));
						}
						relations.add(new Relation(id, members, tags));
					}

					default -> throw new IOException("Unsupported OSM element type: " + e);

				}
			}

			return new OSMData(bounds, nodes, ways, relations);

		} catch (UnsupportedOperationException e) {
			// occurs if the JSON has an unexpected structure
			throw new IOException(e);
		}

	}

	private static class OsmJson {
		public Double version;
		public String generator;
		public List<OsmJsonElement> elements;
	}

	private static class OsmJsonElement {
		public String type;
		public long id;
		public Map<String, String> tags;
		public Double lat;
		public Double lon;
		public List<Long> nodes;
		public List<OsmJsonMember> members;
	}

	private static class OsmJsonMember {
		public String type;
		public long ref;
		public String role;
	}

}
