package org.osm2world.core.world.data;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Nullable;

import org.osm2world.core.target.CommonTarget;
import org.osm2world.core.target.common.mesh.LODRange;
import org.osm2world.core.target.common.mesh.LevelOfDetail;
import org.osm2world.core.target.common.mesh.Mesh;
import org.osm2world.core.target.common.model.ModelInstance;

/**
 * a model which is generated by code during runtime,
 * rather than being loaded as a static asset
 */
public interface ProceduralWorldObject extends WorldObject {

	void buildMeshesAndModels(Target target);

	class Target implements CommonTarget {

		private final List<Mesh> meshes = new ArrayList<>();
		private final List<ModelInstance> subModels = new ArrayList<>();

		private @Nullable LODRange currentLodRange = null;

		public void setCurrentLodRange(LevelOfDetail minLod, LevelOfDetail maxLod) {
			this.currentLodRange = new LODRange(minLod, maxLod);
		}

		@Override
		public void drawMesh(Mesh mesh) {
			if (currentLodRange == null) {
				meshes.add(mesh);
			} else {
				meshes.add(new Mesh(mesh.geometry, mesh.material, currentLodRange.min(), currentLodRange.max()));
			}
		}

		public void addSubModel(ModelInstance subModel) {
			subModels.add(subModel);
		}

	}

	@Override
	default List<Mesh> buildMeshes() {
		var target = new Target();
		buildMeshesAndModels(target);
		return target.meshes;
	}

	@Override
	default List<ModelInstance> getSubModels() {
		var target = new Target();
		buildMeshesAndModels(target);
		return target.subModels;
	}

}
